name: tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 20
          distribution: 'oracle'
          cache: 'maven'
#      - name: Run tests with Maven
#        run: mvn -B test --file pom.xml